// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"sso/internal/domain/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserSaver creates a new instance of MockUserSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserSaver {
	mock := &MockUserSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserSaver is an autogenerated mock type for the UserSaver type
type MockUserSaver struct {
	mock.Mock
}

type MockUserSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserSaver) EXPECT() *MockUserSaver_Expecter {
	return &MockUserSaver_Expecter{mock: &_m.Mock}
}

// SaveUser provides a mock function for the type MockUserSaver
func (_mock *MockUserSaver) SaveUser(ctx context.Context, email string, passHash []byte) (int64, error) {
	ret := _mock.Called(ctx, email, passHash)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (int64, error)); ok {
		return returnFunc(ctx, email, passHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) int64); ok {
		r0 = returnFunc(ctx, email, passHash)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, email, passHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserSaver_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockUserSaver_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passHash []byte
func (_e *MockUserSaver_Expecter) SaveUser(ctx interface{}, email interface{}, passHash interface{}) *MockUserSaver_SaveUser_Call {
	return &MockUserSaver_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, email, passHash)}
}

func (_c *MockUserSaver_SaveUser_Call) Run(run func(ctx context.Context, email string, passHash []byte)) *MockUserSaver_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserSaver_SaveUser_Call) Return(uid int64, err error) *MockUserSaver_SaveUser_Call {
	_c.Call.Return(uid, err)
	return _c
}

func (_c *MockUserSaver_SaveUser_Call) RunAndReturn(run func(ctx context.Context, email string, passHash []byte) (int64, error)) *MockUserSaver_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProvider creates a new instance of MockUserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProvider {
	mock := &MockUserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserProvider is an autogenerated mock type for the UserProvider type
type MockUserProvider struct {
	mock.Mock
}

type MockUserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProvider) EXPECT() *MockUserProvider_Expecter {
	return &MockUserProvider_Expecter{mock: &_m.Mock}
}

// IsAdmin provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) IsAdmin(ctx context.Context, userID int64) (bool, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsAdmin")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_IsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAdmin'
type MockUserProvider_IsAdmin_Call struct {
	*mock.Call
}

// IsAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockUserProvider_Expecter) IsAdmin(ctx interface{}, userID interface{}) *MockUserProvider_IsAdmin_Call {
	return &MockUserProvider_IsAdmin_Call{Call: _e.mock.On("IsAdmin", ctx, userID)}
}

func (_c *MockUserProvider_IsAdmin_Call) Run(run func(ctx context.Context, userID int64)) *MockUserProvider_IsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_IsAdmin_Call) Return(b bool, err error) *MockUserProvider_IsAdmin_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserProvider_IsAdmin_Call) RunAndReturn(run func(ctx context.Context, userID int64) (bool, error)) *MockUserProvider_IsAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) User(ctx context.Context, email string) (models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type MockUserProvider_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserProvider_Expecter) User(ctx interface{}, email interface{}) *MockUserProvider_User_Call {
	return &MockUserProvider_User_Call{Call: _e.mock.On("User", ctx, email)}
}

func (_c *MockUserProvider_User_Call) Run(run func(ctx context.Context, email string)) *MockUserProvider_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_User_Call) Return(user models.User, err error) *MockUserProvider_User_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserProvider_User_Call) RunAndReturn(run func(ctx context.Context, email string) (models.User, error)) *MockUserProvider_User_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAppProvider creates a new instance of MockAppProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppProvider {
	mock := &MockAppProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppProvider is an autogenerated mock type for the AppProvider type
type MockAppProvider struct {
	mock.Mock
}

type MockAppProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppProvider) EXPECT() *MockAppProvider_Expecter {
	return &MockAppProvider_Expecter{mock: &_m.Mock}
}

// App provides a mock function for the type MockAppProvider
func (_mock *MockAppProvider) App(ctx context.Context, appID int) (models.App, error) {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for App")
	}

	var r0 models.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.App, error)); ok {
		return returnFunc(ctx, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.App); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		r0 = ret.Get(0).(models.App)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppProvider_App_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'App'
type MockAppProvider_App_Call struct {
	*mock.Call
}

// App is a helper method to define mock.On call
//   - ctx context.Context
//   - appID int
func (_e *MockAppProvider_Expecter) App(ctx interface{}, appID interface{}) *MockAppProvider_App_Call {
	return &MockAppProvider_App_Call{Call: _e.mock.On("App", ctx, appID)}
}

func (_c *MockAppProvider_App_Call) Run(run func(ctx context.Context, appID int)) *MockAppProvider_App_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppProvider_App_Call) Return(app models.App, err error) *MockAppProvider_App_Call {
	_c.Call.Return(app, err)
	return _c
}

func (_c *MockAppProvider_App_Call) RunAndReturn(run func(ctx context.Context, appID int) (models.App, error)) *MockAppProvider_App_Call {
	_c.Call.Return(run)
	return _c
}
