// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fav_service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFavouritesService creates a new instance of MockFavouritesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFavouritesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFavouritesService {
	mock := &MockFavouritesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFavouritesService is an autogenerated mock type for the FavouritesService type
type MockFavouritesService struct {
	mock.Mock
}

type MockFavouritesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFavouritesService) EXPECT() *MockFavouritesService_Expecter {
	return &MockFavouritesService_Expecter{mock: &_m.Mock}
}

// AddToFavourite provides a mock function for the type MockFavouritesService
func (_mock *MockFavouritesService) AddToFavourite(ctx context.Context, userSSOID int, sneakerID int) error {
	ret := _mock.Called(ctx, userSSOID, sneakerID)

	if len(ret) == 0 {
		panic("no return value specified for AddToFavourite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, userSSOID, sneakerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFavouritesService_AddToFavourite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToFavourite'
type MockFavouritesService_AddToFavourite_Call struct {
	*mock.Call
}

// AddToFavourite is a helper method to define mock.On call
//   - ctx context.Context
//   - userSSOID int
//   - sneakerID int
func (_e *MockFavouritesService_Expecter) AddToFavourite(ctx interface{}, userSSOID interface{}, sneakerID interface{}) *MockFavouritesService_AddToFavourite_Call {
	return &MockFavouritesService_AddToFavourite_Call{Call: _e.mock.On("AddToFavourite", ctx, userSSOID, sneakerID)}
}

func (_c *MockFavouritesService_AddToFavourite_Call) Run(run func(ctx context.Context, userSSOID int, sneakerID int)) *MockFavouritesService_AddToFavourite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFavouritesService_AddToFavourite_Call) Return(err error) *MockFavouritesService_AddToFavourite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFavouritesService_AddToFavourite_Call) RunAndReturn(run func(ctx context.Context, userSSOID int, sneakerID int) error) *MockFavouritesService_AddToFavourite_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllFavourites provides a mock function for the type MockFavouritesService
func (_mock *MockFavouritesService) GetAllFavourites(ctx context.Context, userSSOID int) ([]models.Favourite, error) {
	ret := _mock.Called(ctx, userSSOID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllFavourites")
	}

	var r0 []models.Favourite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.Favourite, error)); ok {
		return returnFunc(ctx, userSSOID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.Favourite); ok {
		r0 = returnFunc(ctx, userSSOID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Favourite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userSSOID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFavouritesService_GetAllFavourites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllFavourites'
type MockFavouritesService_GetAllFavourites_Call struct {
	*mock.Call
}

// GetAllFavourites is a helper method to define mock.On call
//   - ctx context.Context
//   - userSSOID int
func (_e *MockFavouritesService_Expecter) GetAllFavourites(ctx interface{}, userSSOID interface{}) *MockFavouritesService_GetAllFavourites_Call {
	return &MockFavouritesService_GetAllFavourites_Call{Call: _e.mock.On("GetAllFavourites", ctx, userSSOID)}
}

func (_c *MockFavouritesService_GetAllFavourites_Call) Run(run func(ctx context.Context, userSSOID int)) *MockFavouritesService_GetAllFavourites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFavouritesService_GetAllFavourites_Call) Return(favourites []models.Favourite, err error) *MockFavouritesService_GetAllFavourites_Call {
	_c.Call.Return(favourites, err)
	return _c
}

func (_c *MockFavouritesService_GetAllFavourites_Call) RunAndReturn(run func(ctx context.Context, userSSOID int) ([]models.Favourite, error)) *MockFavouritesService_GetAllFavourites_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function for the type MockFavouritesService
func (_mock *MockFavouritesService) GetByIDs(ctx context.Context, ids []int) ([]models.Favourite, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []models.Favourite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) ([]models.Favourite, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) []models.Favourite); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Favourite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFavouritesService_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockFavouritesService_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockFavouritesService_Expecter) GetByIDs(ctx interface{}, ids interface{}) *MockFavouritesService_GetByIDs_Call {
	return &MockFavouritesService_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, ids)}
}

func (_c *MockFavouritesService_GetByIDs_Call) Run(run func(ctx context.Context, ids []int)) *MockFavouritesService_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFavouritesService_GetByIDs_Call) Return(favourites []models.Favourite, err error) *MockFavouritesService_GetByIDs_Call {
	_c.Call.Return(favourites, err)
	return _c
}

func (_c *MockFavouritesService_GetByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []int) ([]models.Favourite, error)) *MockFavouritesService_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// IsFavourite provides a mock function for the type MockFavouritesService
func (_mock *MockFavouritesService) IsFavourite(ctx context.Context, userSSOID int, sneakerID int) (bool, error) {
	ret := _mock.Called(ctx, userSSOID, sneakerID)

	if len(ret) == 0 {
		panic("no return value specified for IsFavourite")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (bool, error)); ok {
		return returnFunc(ctx, userSSOID, sneakerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) bool); ok {
		r0 = returnFunc(ctx, userSSOID, sneakerID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, userSSOID, sneakerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFavouritesService_IsFavourite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFavourite'
type MockFavouritesService_IsFavourite_Call struct {
	*mock.Call
}

// IsFavourite is a helper method to define mock.On call
//   - ctx context.Context
//   - userSSOID int
//   - sneakerID int
func (_e *MockFavouritesService_Expecter) IsFavourite(ctx interface{}, userSSOID interface{}, sneakerID interface{}) *MockFavouritesService_IsFavourite_Call {
	return &MockFavouritesService_IsFavourite_Call{Call: _e.mock.On("IsFavourite", ctx, userSSOID, sneakerID)}
}

func (_c *MockFavouritesService_IsFavourite_Call) Run(run func(ctx context.Context, userSSOID int, sneakerID int)) *MockFavouritesService_IsFavourite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFavouritesService_IsFavourite_Call) Return(b bool, err error) *MockFavouritesService_IsFavourite_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFavouritesService_IsFavourite_Call) RunAndReturn(run func(ctx context.Context, userSSOID int, sneakerID int) (bool, error)) *MockFavouritesService_IsFavourite_Call {
	_c.Call.Return(run)
	return _c
}

// ParseIDsString provides a mock function for the type MockFavouritesService
func (_mock *MockFavouritesService) ParseIDsString(idsParam string) ([]int, error) {
	ret := _mock.Called(idsParam)

	if len(ret) == 0 {
		panic("no return value specified for ParseIDsString")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]int, error)); ok {
		return returnFunc(idsParam)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []int); ok {
		r0 = returnFunc(idsParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(idsParam)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFavouritesService_ParseIDsString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseIDsString'
type MockFavouritesService_ParseIDsString_Call struct {
	*mock.Call
}

// ParseIDsString is a helper method to define mock.On call
//   - idsParam string
func (_e *MockFavouritesService_Expecter) ParseIDsString(idsParam interface{}) *MockFavouritesService_ParseIDsString_Call {
	return &MockFavouritesService_ParseIDsString_Call{Call: _e.mock.On("ParseIDsString", idsParam)}
}

func (_c *MockFavouritesService_ParseIDsString_Call) Run(run func(idsParam string)) *MockFavouritesService_ParseIDsString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFavouritesService_ParseIDsString_Call) Return(ints []int, err error) *MockFavouritesService_ParseIDsString_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockFavouritesService_ParseIDsString_Call) RunAndReturn(run func(idsParam string) ([]int, error)) *MockFavouritesService_ParseIDsString_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFromFavourite provides a mock function for the type MockFavouritesService
func (_mock *MockFavouritesService) RemoveFromFavourite(ctx context.Context, userSSOID int, sneakerID int) error {
	ret := _mock.Called(ctx, userSSOID, sneakerID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromFavourite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, userSSOID, sneakerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFavouritesService_RemoveFromFavourite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFromFavourite'
type MockFavouritesService_RemoveFromFavourite_Call struct {
	*mock.Call
}

// RemoveFromFavourite is a helper method to define mock.On call
//   - ctx context.Context
//   - userSSOID int
//   - sneakerID int
func (_e *MockFavouritesService_Expecter) RemoveFromFavourite(ctx interface{}, userSSOID interface{}, sneakerID interface{}) *MockFavouritesService_RemoveFromFavourite_Call {
	return &MockFavouritesService_RemoveFromFavourite_Call{Call: _e.mock.On("RemoveFromFavourite", ctx, userSSOID, sneakerID)}
}

func (_c *MockFavouritesService_RemoveFromFavourite_Call) Run(run func(ctx context.Context, userSSOID int, sneakerID int)) *MockFavouritesService_RemoveFromFavourite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFavouritesService_RemoveFromFavourite_Call) Return(err error) *MockFavouritesService_RemoveFromFavourite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFavouritesService_RemoveFromFavourite_Call) RunAndReturn(run func(ctx context.Context, userSSOID int, sneakerID int) error) *MockFavouritesService_RemoveFromFavourite_Call {
	_c.Call.Return(run)
	return _c
}
