// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"product_service/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockApp creates a new instance of MockApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApp {
	mock := &MockApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

type MockApp_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApp) EXPECT() *MockApp_Expecter {
	return &MockApp_Expecter{mock: &_m.Mock}
}

// AddSneaker provides a mock function for the type MockApp
func (_mock *MockApp) AddSneaker(ctx context.Context, sneaker *model.Sneaker) (int64, error) {
	ret := _mock.Called(ctx, sneaker)

	if len(ret) == 0 {
		panic("no return value specified for AddSneaker")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Sneaker) (int64, error)); ok {
		return returnFunc(ctx, sneaker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Sneaker) int64); ok {
		r0 = returnFunc(ctx, sneaker)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Sneaker) error); ok {
		r1 = returnFunc(ctx, sneaker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApp_AddSneaker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSneaker'
type MockApp_AddSneaker_Call struct {
	*mock.Call
}

// AddSneaker is a helper method to define mock.On call
//   - ctx context.Context
//   - sneaker *model.Sneaker
func (_e *MockApp_Expecter) AddSneaker(ctx interface{}, sneaker interface{}) *MockApp_AddSneaker_Call {
	return &MockApp_AddSneaker_Call{Call: _e.mock.On("AddSneaker", ctx, sneaker)}
}

func (_c *MockApp_AddSneaker_Call) Run(run func(ctx context.Context, sneaker *model.Sneaker)) *MockApp_AddSneaker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Sneaker
		if args[1] != nil {
			arg1 = args[1].(*model.Sneaker)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApp_AddSneaker_Call) Return(n int64, err error) *MockApp_AddSneaker_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockApp_AddSneaker_Call) RunAndReturn(run func(ctx context.Context, sneaker *model.Sneaker) (int64, error)) *MockApp_AddSneaker_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSneaker provides a mock function for the type MockApp
func (_mock *MockApp) DeleteSneaker(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSneaker")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApp_DeleteSneaker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSneaker'
type MockApp_DeleteSneaker_Call struct {
	*mock.Call
}

// DeleteSneaker is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockApp_Expecter) DeleteSneaker(ctx interface{}, id interface{}) *MockApp_DeleteSneaker_Call {
	return &MockApp_DeleteSneaker_Call{Call: _e.mock.On("DeleteSneaker", ctx, id)}
}

func (_c *MockApp_DeleteSneaker_Call) Run(run func(ctx context.Context, id int64)) *MockApp_DeleteSneaker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApp_DeleteSneaker_Call) Return(err error) *MockApp_DeleteSneaker_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApp_DeleteSneaker_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockApp_DeleteSneaker_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateUploadURL provides a mock function for the type MockApp
func (_mock *MockApp) GenerateUploadURL(ctx context.Context, originalFilename string, contentType string) (string, string, error) {
	ret := _mock.Called(ctx, originalFilename, contentType)

	if len(ret) == 0 {
		panic("no return value specified for GenerateUploadURL")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, string, error)); ok {
		return returnFunc(ctx, originalFilename, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, originalFilename, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, originalFilename, contentType)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, originalFilename, contentType)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockApp_GenerateUploadURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateUploadURL'
type MockApp_GenerateUploadURL_Call struct {
	*mock.Call
}

// GenerateUploadURL is a helper method to define mock.On call
//   - ctx context.Context
//   - originalFilename string
//   - contentType string
func (_e *MockApp_Expecter) GenerateUploadURL(ctx interface{}, originalFilename interface{}, contentType interface{}) *MockApp_GenerateUploadURL_Call {
	return &MockApp_GenerateUploadURL_Call{Call: _e.mock.On("GenerateUploadURL", ctx, originalFilename, contentType)}
}

func (_c *MockApp_GenerateUploadURL_Call) Run(run func(ctx context.Context, originalFilename string, contentType string)) *MockApp_GenerateUploadURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockApp_GenerateUploadURL_Call) Return(uploadURL string, fileKey string, err error) *MockApp_GenerateUploadURL_Call {
	_c.Call.Return(uploadURL, fileKey, err)
	return _c
}

func (_c *MockApp_GenerateUploadURL_Call) RunAndReturn(run func(ctx context.Context, originalFilename string, contentType string) (string, string, error)) *MockApp_GenerateUploadURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllSneakers provides a mock function for the type MockApp
func (_mock *MockApp) GetAllSneakers(ctx context.Context, limit uint64, offset uint64) ([]*model.Sneaker, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSneakers")
	}

	var r0 []*model.Sneaker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]*model.Sneaker, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) []*model.Sneaker); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Sneaker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApp_GetAllSneakers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSneakers'
type MockApp_GetAllSneakers_Call struct {
	*mock.Call
}

// GetAllSneakers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint64
//   - offset uint64
func (_e *MockApp_Expecter) GetAllSneakers(ctx interface{}, limit interface{}, offset interface{}) *MockApp_GetAllSneakers_Call {
	return &MockApp_GetAllSneakers_Call{Call: _e.mock.On("GetAllSneakers", ctx, limit, offset)}
}

func (_c *MockApp_GetAllSneakers_Call) Run(run func(ctx context.Context, limit uint64, offset uint64)) *MockApp_GetAllSneakers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockApp_GetAllSneakers_Call) Return(sneakers []*model.Sneaker, err error) *MockApp_GetAllSneakers_Call {
	_c.Call.Return(sneakers, err)
	return _c
}

func (_c *MockApp_GetAllSneakers_Call) RunAndReturn(run func(ctx context.Context, limit uint64, offset uint64) ([]*model.Sneaker, error)) *MockApp_GetAllSneakers_Call {
	_c.Call.Return(run)
	return _c
}

// GetSneakerByID provides a mock function for the type MockApp
func (_mock *MockApp) GetSneakerByID(ctx context.Context, id int64) (*model.Sneaker, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSneakerByID")
	}

	var r0 *model.Sneaker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*model.Sneaker, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *model.Sneaker); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Sneaker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApp_GetSneakerByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSneakerByID'
type MockApp_GetSneakerByID_Call struct {
	*mock.Call
}

// GetSneakerByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockApp_Expecter) GetSneakerByID(ctx interface{}, id interface{}) *MockApp_GetSneakerByID_Call {
	return &MockApp_GetSneakerByID_Call{Call: _e.mock.On("GetSneakerByID", ctx, id)}
}

func (_c *MockApp_GetSneakerByID_Call) Run(run func(ctx context.Context, id int64)) *MockApp_GetSneakerByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApp_GetSneakerByID_Call) Return(sneaker *model.Sneaker, err error) *MockApp_GetSneakerByID_Call {
	_c.Call.Return(sneaker, err)
	return _c
}

func (_c *MockApp_GetSneakerByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*model.Sneaker, error)) *MockApp_GetSneakerByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSneakersByIDs provides a mock function for the type MockApp
func (_mock *MockApp) GetSneakersByIDs(ctx context.Context, ids []int64) ([]*model.Sneaker, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetSneakersByIDs")
	}

	var r0 []*model.Sneaker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) ([]*model.Sneaker, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) []*model.Sneaker); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Sneaker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApp_GetSneakersByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSneakersByIDs'
type MockApp_GetSneakersByIDs_Call struct {
	*mock.Call
}

// GetSneakersByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockApp_Expecter) GetSneakersByIDs(ctx interface{}, ids interface{}) *MockApp_GetSneakersByIDs_Call {
	return &MockApp_GetSneakersByIDs_Call{Call: _e.mock.On("GetSneakersByIDs", ctx, ids)}
}

func (_c *MockApp_GetSneakersByIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockApp_GetSneakersByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApp_GetSneakersByIDs_Call) Return(sneakers []*model.Sneaker, err error) *MockApp_GetSneakersByIDs_Call {
	_c.Call.Return(sneakers, err)
	return _c
}

func (_c *MockApp_GetSneakersByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []int64) ([]*model.Sneaker, error)) *MockApp_GetSneakersByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProductImage provides a mock function for the type MockApp
func (_mock *MockApp) UpdateProductImage(ctx context.Context, productID int64, imageKey string) error {
	ret := _mock.Called(ctx, productID, imageKey)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProductImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, productID, imageKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApp_UpdateProductImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProductImage'
type MockApp_UpdateProductImage_Call struct {
	*mock.Call
}

// UpdateProductImage is a helper method to define mock.On call
//   - ctx context.Context
//   - productID int64
//   - imageKey string
func (_e *MockApp_Expecter) UpdateProductImage(ctx interface{}, productID interface{}, imageKey interface{}) *MockApp_UpdateProductImage_Call {
	return &MockApp_UpdateProductImage_Call{Call: _e.mock.On("UpdateProductImage", ctx, productID, imageKey)}
}

func (_c *MockApp_UpdateProductImage_Call) Run(run func(ctx context.Context, productID int64, imageKey string)) *MockApp_UpdateProductImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockApp_UpdateProductImage_Call) Return(err error) *MockApp_UpdateProductImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApp_UpdateProductImage_Call) RunAndReturn(run func(ctx context.Context, productID int64, imageKey string) error) *MockApp_UpdateProductImage_Call {
	_c.Call.Return(run)
	return _c
}
