// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"cart_service/internal/models"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCartRepository creates a new instance of MockCartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartRepository {
	mock := &MockCartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCartRepository is an autogenerated mock type for the CartRepository type
type MockCartRepository struct {
	mock.Mock
}

type MockCartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartRepository) EXPECT() *MockCartRepository_Expecter {
	return &MockCartRepository_Expecter{mock: &_m.Mock}
}

// AddCartItem provides a mock function for the type MockCartRepository
func (_mock *MockCartRepository) AddCartItem(ctx context.Context, item *models.CartItem) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for AddCartItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.CartItem) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartRepository_AddCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCartItem'
type MockCartRepository_AddCartItem_Call struct {
	*mock.Call
}

// AddCartItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *models.CartItem
func (_e *MockCartRepository_Expecter) AddCartItem(ctx interface{}, item interface{}) *MockCartRepository_AddCartItem_Call {
	return &MockCartRepository_AddCartItem_Call{Call: _e.mock.On("AddCartItem", ctx, item)}
}

func (_c *MockCartRepository_AddCartItem_Call) Run(run func(ctx context.Context, item *models.CartItem)) *MockCartRepository_AddCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.CartItem
		if args[1] != nil {
			arg1 = args[1].(*models.CartItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartRepository_AddCartItem_Call) Return(err error) *MockCartRepository_AddCartItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartRepository_AddCartItem_Call) RunAndReturn(run func(ctx context.Context, item *models.CartItem) error) *MockCartRepository_AddCartItem_Call {
	_c.Call.Return(run)
	return _c
}

// ClearCart provides a mock function for the type MockCartRepository
func (_mock *MockCartRepository) ClearCart(ctx context.Context, userSSOID int) error {
	ret := _mock.Called(ctx, userSSOID)

	if len(ret) == 0 {
		panic("no return value specified for ClearCart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userSSOID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartRepository_ClearCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCart'
type MockCartRepository_ClearCart_Call struct {
	*mock.Call
}

// ClearCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userSSOID int
func (_e *MockCartRepository_Expecter) ClearCart(ctx interface{}, userSSOID interface{}) *MockCartRepository_ClearCart_Call {
	return &MockCartRepository_ClearCart_Call{Call: _e.mock.On("ClearCart", ctx, userSSOID)}
}

func (_c *MockCartRepository_ClearCart_Call) Run(run func(ctx context.Context, userSSOID int)) *MockCartRepository_ClearCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartRepository_ClearCart_Call) Return(err error) *MockCartRepository_ClearCart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartRepository_ClearCart_Call) RunAndReturn(run func(ctx context.Context, userSSOID int) error) *MockCartRepository_ClearCart_Call {
	_c.Call.Return(run)
	return _c
}

// GetCart provides a mock function for the type MockCartRepository
func (_mock *MockCartRepository) GetCart(ctx context.Context, userSSOID int) (*models.Cart, error) {
	ret := _mock.Called(ctx, userSSOID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 *models.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Cart, error)); ok {
		return returnFunc(ctx, userSSOID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Cart); ok {
		r0 = returnFunc(ctx, userSSOID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userSSOID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCartRepository_GetCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCart'
type MockCartRepository_GetCart_Call struct {
	*mock.Call
}

// GetCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userSSOID int
func (_e *MockCartRepository_Expecter) GetCart(ctx interface{}, userSSOID interface{}) *MockCartRepository_GetCart_Call {
	return &MockCartRepository_GetCart_Call{Call: _e.mock.On("GetCart", ctx, userSSOID)}
}

func (_c *MockCartRepository_GetCart_Call) Run(run func(ctx context.Context, userSSOID int)) *MockCartRepository_GetCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartRepository_GetCart_Call) Return(cart *models.Cart, err error) *MockCartRepository_GetCart_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *MockCartRepository_GetCart_Call) RunAndReturn(run func(ctx context.Context, userSSOID int) (*models.Cart, error)) *MockCartRepository_GetCart_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCartItem provides a mock function for the type MockCartRepository
func (_mock *MockCartRepository) RemoveCartItem(ctx context.Context, userSSOID int, itemID string) error {
	ret := _mock.Called(ctx, userSSOID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCartItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userSSOID, itemID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartRepository_RemoveCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCartItem'
type MockCartRepository_RemoveCartItem_Call struct {
	*mock.Call
}

// RemoveCartItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userSSOID int
//   - itemID string
func (_e *MockCartRepository_Expecter) RemoveCartItem(ctx interface{}, userSSOID interface{}, itemID interface{}) *MockCartRepository_RemoveCartItem_Call {
	return &MockCartRepository_RemoveCartItem_Call{Call: _e.mock.On("RemoveCartItem", ctx, userSSOID, itemID)}
}

func (_c *MockCartRepository_RemoveCartItem_Call) Run(run func(ctx context.Context, userSSOID int, itemID string)) *MockCartRepository_RemoveCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCartRepository_RemoveCartItem_Call) Return(err error) *MockCartRepository_RemoveCartItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartRepository_RemoveCartItem_Call) RunAndReturn(run func(ctx context.Context, userSSOID int, itemID string) error) *MockCartRepository_RemoveCartItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCartItemQuantity provides a mock function for the type MockCartRepository
func (_mock *MockCartRepository) UpdateCartItemQuantity(ctx context.Context, userSSOID int, itemID string, quantity int) error {
	ret := _mock.Called(ctx, userSSOID, itemID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCartItemQuantity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, int) error); ok {
		r0 = returnFunc(ctx, userSSOID, itemID, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartRepository_UpdateCartItemQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCartItemQuantity'
type MockCartRepository_UpdateCartItemQuantity_Call struct {
	*mock.Call
}

// UpdateCartItemQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - userSSOID int
//   - itemID string
//   - quantity int
func (_e *MockCartRepository_Expecter) UpdateCartItemQuantity(ctx interface{}, userSSOID interface{}, itemID interface{}, quantity interface{}) *MockCartRepository_UpdateCartItemQuantity_Call {
	return &MockCartRepository_UpdateCartItemQuantity_Call{Call: _e.mock.On("UpdateCartItemQuantity", ctx, userSSOID, itemID, quantity)}
}

func (_c *MockCartRepository_UpdateCartItemQuantity_Call) Run(run func(ctx context.Context, userSSOID int, itemID string, quantity int)) *MockCartRepository_UpdateCartItemQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCartRepository_UpdateCartItemQuantity_Call) Return(err error) *MockCartRepository_UpdateCartItemQuantity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartRepository_UpdateCartItemQuantity_Call) RunAndReturn(run func(ctx context.Context, userSSOID int, itemID string, quantity int) error) *MockCartRepository_UpdateCartItemQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCartCache creates a new instance of MockCartCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartCache {
	mock := &MockCartCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCartCache is an autogenerated mock type for the CartCache type
type MockCartCache struct {
	mock.Mock
}

type MockCartCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartCache) EXPECT() *MockCartCache_Expecter {
	return &MockCartCache_Expecter{mock: &_m.Mock}
}

// AddToCartItem provides a mock function for the type MockCartCache
func (_mock *MockCartCache) AddToCartItem(ctx context.Context, item models.CartItem) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for AddToCartItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.CartItem) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartCache_AddToCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToCartItem'
type MockCartCache_AddToCartItem_Call struct {
	*mock.Call
}

// AddToCartItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item models.CartItem
func (_e *MockCartCache_Expecter) AddToCartItem(ctx interface{}, item interface{}) *MockCartCache_AddToCartItem_Call {
	return &MockCartCache_AddToCartItem_Call{Call: _e.mock.On("AddToCartItem", ctx, item)}
}

func (_c *MockCartCache_AddToCartItem_Call) Run(run func(ctx context.Context, item models.CartItem)) *MockCartCache_AddToCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.CartItem
		if args[1] != nil {
			arg1 = args[1].(models.CartItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartCache_AddToCartItem_Call) Return(err error) *MockCartCache_AddToCartItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartCache_AddToCartItem_Call) RunAndReturn(run func(ctx context.Context, item models.CartItem) error) *MockCartCache_AddToCartItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetCart provides a mock function for the type MockCartCache
func (_mock *MockCartCache) GetCart(ctx context.Context, userSSOID int) (*models.Cart, error) {
	ret := _mock.Called(ctx, userSSOID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 *models.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Cart, error)); ok {
		return returnFunc(ctx, userSSOID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Cart); ok {
		r0 = returnFunc(ctx, userSSOID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userSSOID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCartCache_GetCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCart'
type MockCartCache_GetCart_Call struct {
	*mock.Call
}

// GetCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userSSOID int
func (_e *MockCartCache_Expecter) GetCart(ctx interface{}, userSSOID interface{}) *MockCartCache_GetCart_Call {
	return &MockCartCache_GetCart_Call{Call: _e.mock.On("GetCart", ctx, userSSOID)}
}

func (_c *MockCartCache_GetCart_Call) Run(run func(ctx context.Context, userSSOID int)) *MockCartCache_GetCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartCache_GetCart_Call) Return(cart *models.Cart, err error) *MockCartCache_GetCart_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *MockCartCache_GetCart_Call) RunAndReturn(run func(ctx context.Context, userSSOID int) (*models.Cart, error)) *MockCartCache_GetCart_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateCart provides a mock function for the type MockCartCache
func (_mock *MockCartCache) InvalidateCart(ctx context.Context, userSSOID int) error {
	ret := _mock.Called(ctx, userSSOID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateCart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userSSOID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartCache_InvalidateCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateCart'
type MockCartCache_InvalidateCart_Call struct {
	*mock.Call
}

// InvalidateCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userSSOID int
func (_e *MockCartCache_Expecter) InvalidateCart(ctx interface{}, userSSOID interface{}) *MockCartCache_InvalidateCart_Call {
	return &MockCartCache_InvalidateCart_Call{Call: _e.mock.On("InvalidateCart", ctx, userSSOID)}
}

func (_c *MockCartCache_InvalidateCart_Call) Run(run func(ctx context.Context, userSSOID int)) *MockCartCache_InvalidateCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartCache_InvalidateCart_Call) Return(err error) *MockCartCache_InvalidateCart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartCache_InvalidateCart_Call) RunAndReturn(run func(ctx context.Context, userSSOID int) error) *MockCartCache_InvalidateCart_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFromCart provides a mock function for the type MockCartCache
func (_mock *MockCartCache) RemoveFromCart(ctx context.Context, userSSOID int, itemID string) error {
	ret := _mock.Called(ctx, userSSOID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromCart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userSSOID, itemID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartCache_RemoveFromCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFromCart'
type MockCartCache_RemoveFromCart_Call struct {
	*mock.Call
}

// RemoveFromCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userSSOID int
//   - itemID string
func (_e *MockCartCache_Expecter) RemoveFromCart(ctx interface{}, userSSOID interface{}, itemID interface{}) *MockCartCache_RemoveFromCart_Call {
	return &MockCartCache_RemoveFromCart_Call{Call: _e.mock.On("RemoveFromCart", ctx, userSSOID, itemID)}
}

func (_c *MockCartCache_RemoveFromCart_Call) Run(run func(ctx context.Context, userSSOID int, itemID string)) *MockCartCache_RemoveFromCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCartCache_RemoveFromCart_Call) Return(err error) *MockCartCache_RemoveFromCart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartCache_RemoveFromCart_Call) RunAndReturn(run func(ctx context.Context, userSSOID int, itemID string) error) *MockCartCache_RemoveFromCart_Call {
	_c.Call.Return(run)
	return _c
}

// SetCart provides a mock function for the type MockCartCache
func (_mock *MockCartCache) SetCart(ctx context.Context, userSSOID int, cart *models.Cart, ttl time.Duration) error {
	ret := _mock.Called(ctx, userSSOID, cart, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetCart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *models.Cart, time.Duration) error); ok {
		r0 = returnFunc(ctx, userSSOID, cart, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartCache_SetCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCart'
type MockCartCache_SetCart_Call struct {
	*mock.Call
}

// SetCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userSSOID int
//   - cart *models.Cart
//   - ttl time.Duration
func (_e *MockCartCache_Expecter) SetCart(ctx interface{}, userSSOID interface{}, cart interface{}, ttl interface{}) *MockCartCache_SetCart_Call {
	return &MockCartCache_SetCart_Call{Call: _e.mock.On("SetCart", ctx, userSSOID, cart, ttl)}
}

func (_c *MockCartCache_SetCart_Call) Run(run func(ctx context.Context, userSSOID int, cart *models.Cart, ttl time.Duration)) *MockCartCache_SetCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *models.Cart
		if args[2] != nil {
			arg2 = args[2].(*models.Cart)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCartCache_SetCart_Call) Return(err error) *MockCartCache_SetCart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartCache_SetCart_Call) RunAndReturn(run func(ctx context.Context, userSSOID int, cart *models.Cart, ttl time.Duration) error) *MockCartCache_SetCart_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCartItemQuantity provides a mock function for the type MockCartCache
func (_mock *MockCartCache) UpdateCartItemQuantity(ctx context.Context, userSSOID int, itemID string, newQuantity int) error {
	ret := _mock.Called(ctx, userSSOID, itemID, newQuantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCartItemQuantity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, int) error); ok {
		r0 = returnFunc(ctx, userSSOID, itemID, newQuantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartCache_UpdateCartItemQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCartItemQuantity'
type MockCartCache_UpdateCartItemQuantity_Call struct {
	*mock.Call
}

// UpdateCartItemQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - userSSOID int
//   - itemID string
//   - newQuantity int
func (_e *MockCartCache_Expecter) UpdateCartItemQuantity(ctx interface{}, userSSOID interface{}, itemID interface{}, newQuantity interface{}) *MockCartCache_UpdateCartItemQuantity_Call {
	return &MockCartCache_UpdateCartItemQuantity_Call{Call: _e.mock.On("UpdateCartItemQuantity", ctx, userSSOID, itemID, newQuantity)}
}

func (_c *MockCartCache_UpdateCartItemQuantity_Call) Run(run func(ctx context.Context, userSSOID int, itemID string, newQuantity int)) *MockCartCache_UpdateCartItemQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCartCache_UpdateCartItemQuantity_Call) Return(err error) *MockCartCache_UpdateCartItemQuantity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartCache_UpdateCartItemQuantity_Call) RunAndReturn(run func(ctx context.Context, userSSOID int, itemID string, newQuantity int) error) *MockCartCache_UpdateCartItemQuantity_Call {
	_c.Call.Return(run)
	return _c
}
