// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"order_service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type MockService
func (_mock *MockService) CreateOrder(ctx context.Context, userID int, items []models.OrderItem) (*models.OrderWithItems, error) {
	ret := _mock.Called(ctx, userID, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *models.OrderWithItems
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []models.OrderItem) (*models.OrderWithItems, error)); ok {
		return returnFunc(ctx, userID, items)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []models.OrderItem) *models.OrderWithItems); ok {
		r0 = returnFunc(ctx, userID, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrderWithItems)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, []models.OrderItem) error); ok {
		r1 = returnFunc(ctx, userID, items)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - items []models.OrderItem
func (_e *MockService_Expecter) CreateOrder(ctx interface{}, userID interface{}, items interface{}) *MockService_CreateOrder_Call {
	return &MockService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userID, items)}
}

func (_c *MockService_CreateOrder_Call) Run(run func(ctx context.Context, userID int, items []models.OrderItem)) *MockService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []models.OrderItem
		if args[2] != nil {
			arg2 = args[2].([]models.OrderItem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CreateOrder_Call) Return(orderWithItems *models.OrderWithItems, err error) *MockService_CreateOrder_Call {
	_c.Call.Return(orderWithItems, err)
	return _c
}

func (_c *MockService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, userID int, items []models.OrderItem) (*models.OrderWithItems, error)) *MockService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type MockService
func (_mock *MockService) GetOrder(ctx context.Context, orderID int) (*models.OrderWithItems, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *models.OrderWithItems
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.OrderWithItems, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.OrderWithItems); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrderWithItems)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID int
func (_e *MockService_Expecter) GetOrder(ctx interface{}, orderID interface{}) *MockService_GetOrder_Call {
	return &MockService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderID)}
}

func (_c *MockService_GetOrder_Call) Run(run func(ctx context.Context, orderID int)) *MockService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetOrder_Call) Return(orderWithItems *models.OrderWithItems, err error) *MockService_GetOrder_Call {
	_c.Call.Return(orderWithItems, err)
	return _c
}

func (_c *MockService_GetOrder_Call) RunAndReturn(run func(ctx context.Context, orderID int) (*models.OrderWithItems, error)) *MockService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserOrders provides a mock function for the type MockService
func (_mock *MockService) GetUserOrders(ctx context.Context, userID int) ([]*models.OrderWithItems, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrders")
	}

	var r0 []*models.OrderWithItems
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.OrderWithItems, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.OrderWithItems); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.OrderWithItems)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetUserOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserOrders'
type MockService_GetUserOrders_Call struct {
	*mock.Call
}

// GetUserOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockService_Expecter) GetUserOrders(ctx interface{}, userID interface{}) *MockService_GetUserOrders_Call {
	return &MockService_GetUserOrders_Call{Call: _e.mock.On("GetUserOrders", ctx, userID)}
}

func (_c *MockService_GetUserOrders_Call) Run(run func(ctx context.Context, userID int)) *MockService_GetUserOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetUserOrders_Call) Return(orderWithItemss []*models.OrderWithItems, err error) *MockService_GetUserOrders_Call {
	_c.Call.Return(orderWithItemss, err)
	return _c
}

func (_c *MockService_GetUserOrders_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]*models.OrderWithItems, error)) *MockService_GetUserOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function for the type MockService
func (_mock *MockService) UpdateOrderStatus(ctx context.Context, orderID int, status string) error {
	ret := _mock.Called(ctx, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, orderID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type MockService_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID int
//   - status string
func (_e *MockService_Expecter) UpdateOrderStatus(ctx interface{}, orderID interface{}, status interface{}) *MockService_UpdateOrderStatus_Call {
	return &MockService_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", ctx, orderID, status)}
}

func (_c *MockService_UpdateOrderStatus_Call) Run(run func(ctx context.Context, orderID int, status string)) *MockService_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UpdateOrderStatus_Call) Return(err error) *MockService_UpdateOrderStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateOrderStatus_Call) RunAndReturn(run func(ctx context.Context, orderID int, status string) error) *MockService_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessWebhook provides a mock function for the type MockService
func (_mock *MockService) ProcessWebhook(ctx context.Context, yookassaID string, status string) error {
	ret := _mock.Called(ctx, yookassaID, status)

	if len(ret) == 0 {
		panic("no return value specified for ProcessWebhook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, yookassaID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}
