// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"product_service/internal/model"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProductPostgres creates a new instance of MockProductPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductPostgres {
	mock := &MockProductPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductPostgres is an autogenerated mock type for the ProductPostgres type
type MockProductPostgres struct {
	mock.Mock
}

type MockProductPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductPostgres) EXPECT() *MockProductPostgres_Expecter {
	return &MockProductPostgres_Expecter{mock: &_m.Mock}
}

// AddSneaker provides a mock function for the type MockProductPostgres
func (_mock *MockProductPostgres) AddSneaker(ctx context.Context, sneaker *model.Sneaker) (int64, error) {
	ret := _mock.Called(ctx, sneaker)

	if len(ret) == 0 {
		panic("no return value specified for AddSneaker")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Sneaker) (int64, error)); ok {
		return returnFunc(ctx, sneaker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Sneaker) int64); ok {
		r0 = returnFunc(ctx, sneaker)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Sneaker) error); ok {
		r1 = returnFunc(ctx, sneaker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductPostgres_AddSneaker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSneaker'
type MockProductPostgres_AddSneaker_Call struct {
	*mock.Call
}

// AddSneaker is a helper method to define mock.On call
//   - ctx context.Context
//   - sneaker *model.Sneaker
func (_e *MockProductPostgres_Expecter) AddSneaker(ctx interface{}, sneaker interface{}) *MockProductPostgres_AddSneaker_Call {
	return &MockProductPostgres_AddSneaker_Call{Call: _e.mock.On("AddSneaker", ctx, sneaker)}
}

func (_c *MockProductPostgres_AddSneaker_Call) Run(run func(ctx context.Context, sneaker *model.Sneaker)) *MockProductPostgres_AddSneaker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Sneaker
		if args[1] != nil {
			arg1 = args[1].(*model.Sneaker)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductPostgres_AddSneaker_Call) Return(n int64, err error) *MockProductPostgres_AddSneaker_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockProductPostgres_AddSneaker_Call) RunAndReturn(run func(ctx context.Context, sneaker *model.Sneaker) (int64, error)) *MockProductPostgres_AddSneaker_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSneaker provides a mock function for the type MockProductPostgres
func (_mock *MockProductPostgres) DeleteSneaker(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSneaker")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductPostgres_DeleteSneaker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSneaker'
type MockProductPostgres_DeleteSneaker_Call struct {
	*mock.Call
}

// DeleteSneaker is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockProductPostgres_Expecter) DeleteSneaker(ctx interface{}, id interface{}) *MockProductPostgres_DeleteSneaker_Call {
	return &MockProductPostgres_DeleteSneaker_Call{Call: _e.mock.On("DeleteSneaker", ctx, id)}
}

func (_c *MockProductPostgres_DeleteSneaker_Call) Run(run func(ctx context.Context, id int64)) *MockProductPostgres_DeleteSneaker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductPostgres_DeleteSneaker_Call) Return(err error) *MockProductPostgres_DeleteSneaker_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductPostgres_DeleteSneaker_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockProductPostgres_DeleteSneaker_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllSneakers provides a mock function for the type MockProductPostgres
func (_mock *MockProductPostgres) GetAllSneakers(ctx context.Context, limit uint64, offset uint64) ([]*model.Sneaker, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSneakers")
	}

	var r0 []*model.Sneaker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]*model.Sneaker, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) []*model.Sneaker); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Sneaker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductPostgres_GetAllSneakers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSneakers'
type MockProductPostgres_GetAllSneakers_Call struct {
	*mock.Call
}

// GetAllSneakers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint64
//   - offset uint64
func (_e *MockProductPostgres_Expecter) GetAllSneakers(ctx interface{}, limit interface{}, offset interface{}) *MockProductPostgres_GetAllSneakers_Call {
	return &MockProductPostgres_GetAllSneakers_Call{Call: _e.mock.On("GetAllSneakers", ctx, limit, offset)}
}

func (_c *MockProductPostgres_GetAllSneakers_Call) Run(run func(ctx context.Context, limit uint64, offset uint64)) *MockProductPostgres_GetAllSneakers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProductPostgres_GetAllSneakers_Call) Return(sneakers []*model.Sneaker, err error) *MockProductPostgres_GetAllSneakers_Call {
	_c.Call.Return(sneakers, err)
	return _c
}

func (_c *MockProductPostgres_GetAllSneakers_Call) RunAndReturn(run func(ctx context.Context, limit uint64, offset uint64) ([]*model.Sneaker, error)) *MockProductPostgres_GetAllSneakers_Call {
	_c.Call.Return(run)
	return _c
}

// GetSneakerByID provides a mock function for the type MockProductPostgres
func (_mock *MockProductPostgres) GetSneakerByID(ctx context.Context, id int64) (*model.Sneaker, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSneakerByID")
	}

	var r0 *model.Sneaker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*model.Sneaker, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *model.Sneaker); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Sneaker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductPostgres_GetSneakerByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSneakerByID'
type MockProductPostgres_GetSneakerByID_Call struct {
	*mock.Call
}

// GetSneakerByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockProductPostgres_Expecter) GetSneakerByID(ctx interface{}, id interface{}) *MockProductPostgres_GetSneakerByID_Call {
	return &MockProductPostgres_GetSneakerByID_Call{Call: _e.mock.On("GetSneakerByID", ctx, id)}
}

func (_c *MockProductPostgres_GetSneakerByID_Call) Run(run func(ctx context.Context, id int64)) *MockProductPostgres_GetSneakerByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductPostgres_GetSneakerByID_Call) Return(sneaker *model.Sneaker, err error) *MockProductPostgres_GetSneakerByID_Call {
	_c.Call.Return(sneaker, err)
	return _c
}

func (_c *MockProductPostgres_GetSneakerByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*model.Sneaker, error)) *MockProductPostgres_GetSneakerByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSneakersByIDs provides a mock function for the type MockProductPostgres
func (_mock *MockProductPostgres) GetSneakersByIDs(ctx context.Context, ids []int64) ([]*model.Sneaker, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetSneakersByIDs")
	}

	var r0 []*model.Sneaker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) ([]*model.Sneaker, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) []*model.Sneaker); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Sneaker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductPostgres_GetSneakersByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSneakersByIDs'
type MockProductPostgres_GetSneakersByIDs_Call struct {
	*mock.Call
}

// GetSneakersByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockProductPostgres_Expecter) GetSneakersByIDs(ctx interface{}, ids interface{}) *MockProductPostgres_GetSneakersByIDs_Call {
	return &MockProductPostgres_GetSneakersByIDs_Call{Call: _e.mock.On("GetSneakersByIDs", ctx, ids)}
}

func (_c *MockProductPostgres_GetSneakersByIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockProductPostgres_GetSneakersByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductPostgres_GetSneakersByIDs_Call) Return(sneakers []*model.Sneaker, err error) *MockProductPostgres_GetSneakersByIDs_Call {
	_c.Call.Return(sneakers, err)
	return _c
}

func (_c *MockProductPostgres_GetSneakersByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []int64) ([]*model.Sneaker, error)) *MockProductPostgres_GetSneakersByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateImageKey provides a mock function for the type MockProductPostgres
func (_mock *MockProductPostgres) UpdateImageKey(ctx context.Context, id int64, imageKey string) error {
	ret := _mock.Called(ctx, id, imageKey)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImageKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, id, imageKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductPostgres_UpdateImageKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateImageKey'
type MockProductPostgres_UpdateImageKey_Call struct {
	*mock.Call
}

// UpdateImageKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - imageKey string
func (_e *MockProductPostgres_Expecter) UpdateImageKey(ctx interface{}, id interface{}, imageKey interface{}) *MockProductPostgres_UpdateImageKey_Call {
	return &MockProductPostgres_UpdateImageKey_Call{Call: _e.mock.On("UpdateImageKey", ctx, id, imageKey)}
}

func (_c *MockProductPostgres_UpdateImageKey_Call) Run(run func(ctx context.Context, id int64, imageKey string)) *MockProductPostgres_UpdateImageKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProductPostgres_UpdateImageKey_Call) Return(err error) *MockProductPostgres_UpdateImageKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductPostgres_UpdateImageKey_Call) RunAndReturn(run func(ctx context.Context, id int64, imageKey string) error) *MockProductPostgres_UpdateImageKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductCache creates a new instance of MockProductCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductCache {
	mock := &MockProductCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductCache is an autogenerated mock type for the ProductCache type
type MockProductCache struct {
	mock.Mock
}

type MockProductCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductCache) EXPECT() *MockProductCache_Expecter {
	return &MockProductCache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockProductCache
func (_mock *MockProductCache) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockProductCache_Expecter) Delete(ctx interface{}, key interface{}) *MockProductCache_Delete_Call {
	return &MockProductCache_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockProductCache_Delete_Call) Run(run func(ctx context.Context, key string)) *MockProductCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductCache_Delete_Call) Return(err error) *MockProductCache_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductCache_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockProductCache_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByPrefix provides a mock function for the type MockProductCache
func (_mock *MockProductCache) DeleteByPrefix(ctx context.Context, prefix string) error {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPrefix")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductCache_DeleteByPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByPrefix'
type MockProductCache_DeleteByPrefix_Call struct {
	*mock.Call
}

// DeleteByPrefix is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockProductCache_Expecter) DeleteByPrefix(ctx interface{}, prefix interface{}) *MockProductCache_DeleteByPrefix_Call {
	return &MockProductCache_DeleteByPrefix_Call{Call: _e.mock.On("DeleteByPrefix", ctx, prefix)}
}

func (_c *MockProductCache_DeleteByPrefix_Call) Run(run func(ctx context.Context, prefix string)) *MockProductCache_DeleteByPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductCache_DeleteByPrefix_Call) Return(err error) *MockProductCache_DeleteByPrefix_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductCache_DeleteByPrefix_Call) RunAndReturn(run func(ctx context.Context, prefix string) error) *MockProductCache_DeleteByPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockProductCache
func (_mock *MockProductCache) Get(ctx context.Context, key string, dest interface{}) error {
	ret := _mock.Called(ctx, key, dest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = returnFunc(ctx, key, dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProductCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - dest interface{}
func (_e *MockProductCache_Expecter) Get(ctx interface{}, key interface{}, dest interface{}) *MockProductCache_Get_Call {
	return &MockProductCache_Get_Call{Call: _e.mock.On("Get", ctx, key, dest)}
}

func (_c *MockProductCache_Get_Call) Run(run func(ctx context.Context, key string, dest interface{})) *MockProductCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProductCache_Get_Call) Return(err error) *MockProductCache_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductCache_Get_Call) RunAndReturn(run func(ctx context.Context, key string, dest interface{}) error) *MockProductCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockProductCache
func (_mock *MockProductCache) Set(ctx context.Context, key string, value interface{}, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockProductCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - ttl time.Duration
func (_e *MockProductCache_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockProductCache_Set_Call {
	return &MockProductCache_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *MockProductCache_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, ttl time.Duration)) *MockProductCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProductCache_Set_Call) Return(err error) *MockProductCache_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductCache_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value interface{}, ttl time.Duration) error) *MockProductCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileStore creates a new instance of MockFileStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileStore {
	mock := &MockFileStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileStore is an autogenerated mock type for the FileStore type
type MockFileStore struct {
	mock.Mock
}

type MockFileStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileStore) EXPECT() *MockFileStore_Expecter {
	return &MockFileStore_Expecter{mock: &_m.Mock}
}

// GenerateUploadURL provides a mock function for the type MockFileStore
func (_mock *MockFileStore) GenerateUploadURL(ctx context.Context, key string, contentType string) (string, error) {
	ret := _mock.Called(ctx, key, contentType)

	if len(ret) == 0 {
		panic("no return value specified for GenerateUploadURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, key, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, key, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, key, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStore_GenerateUploadURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateUploadURL'
type MockFileStore_GenerateUploadURL_Call struct {
	*mock.Call
}

// GenerateUploadURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - contentType string
func (_e *MockFileStore_Expecter) GenerateUploadURL(ctx interface{}, key interface{}, contentType interface{}) *MockFileStore_GenerateUploadURL_Call {
	return &MockFileStore_GenerateUploadURL_Call{Call: _e.mock.On("GenerateUploadURL", ctx, key, contentType)}
}

func (_c *MockFileStore_GenerateUploadURL_Call) Run(run func(ctx context.Context, key string, contentType string)) *MockFileStore_GenerateUploadURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileStore_GenerateUploadURL_Call) Return(s string, err error) *MockFileStore_GenerateUploadURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileStore_GenerateUploadURL_Call) RunAndReturn(run func(ctx context.Context, key string, contentType string) (string, error)) *MockFileStore_GenerateUploadURL_Call {
	_c.Call.Return(run)
	return _c
}
