env: "local" 

# Настройки HTTP-сервера
http_server:
  address: "0.0.0.0:8081"
  timeout: "10s"
  idle_timeout: "60s"
  cors_allowed:
    - "http://localhost:5173"

# Настройки Redis
redis:
  host: "cart_redis"  # Используем имя сервиса из docker-compose
  port: 6379
  password: ""
  db: 0
  expiration: "168h"  # 7 дней

postgres:
  host: "cart_postgres"
  port: 5432
  user: "cart_user"
  password: "cart_password"
  dbname: "cart_db"
  sslmode: "disable"
  max_connections: 10
  connection_timeout: 5