// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuth creates a new instance of MockAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuth {
	mock := &MockAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuth is an autogenerated mock type for the Auth type
type MockAuth struct {
	mock.Mock
}

type MockAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuth) EXPECT() *MockAuth_Expecter {
	return &MockAuth_Expecter{mock: &_m.Mock}
}

// IsAdmin provides a mock function for the type MockAuth
func (_mock *MockAuth) IsAdmin(ctx context.Context, userID int64) (bool, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsAdmin")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuth_IsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAdmin'
type MockAuth_IsAdmin_Call struct {
	*mock.Call
}

// IsAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAuth_Expecter) IsAdmin(ctx interface{}, userID interface{}) *MockAuth_IsAdmin_Call {
	return &MockAuth_IsAdmin_Call{Call: _e.mock.On("IsAdmin", ctx, userID)}
}

func (_c *MockAuth_IsAdmin_Call) Run(run func(ctx context.Context, userID int64)) *MockAuth_IsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuth_IsAdmin_Call) Return(b bool, err error) *MockAuth_IsAdmin_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAuth_IsAdmin_Call) RunAndReturn(run func(ctx context.Context, userID int64) (bool, error)) *MockAuth_IsAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuth
func (_mock *MockAuth) Login(ctx context.Context, email string, password string, appID int) (string, error) {
	ret := _mock.Called(ctx, email, password, appID)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) (string, error)); ok {
		return returnFunc(ctx, email, password, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) string); ok {
		r0 = returnFunc(ctx, email, password, appID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = returnFunc(ctx, email, password, appID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuth_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuth_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - appID int
func (_e *MockAuth_Expecter) Login(ctx interface{}, email interface{}, password interface{}, appID interface{}) *MockAuth_Login_Call {
	return &MockAuth_Login_Call{Call: _e.mock.On("Login", ctx, email, password, appID)}
}

func (_c *MockAuth_Login_Call) Run(run func(ctx context.Context, email string, password string, appID int)) *MockAuth_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuth_Login_Call) Return(token string, err error) *MockAuth_Login_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockAuth_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string, appID int) (string, error)) *MockAuth_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterNewUser provides a mock function for the type MockAuth
func (_mock *MockAuth) RegisterNewUser(ctx context.Context, email string, password string) (int64, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterNewUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuth_RegisterNewUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterNewUser'
type MockAuth_RegisterNewUser_Call struct {
	*mock.Call
}

// RegisterNewUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuth_Expecter) RegisterNewUser(ctx interface{}, email interface{}, password interface{}) *MockAuth_RegisterNewUser_Call {
	return &MockAuth_RegisterNewUser_Call{Call: _e.mock.On("RegisterNewUser", ctx, email, password)}
}

func (_c *MockAuth_RegisterNewUser_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuth_RegisterNewUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuth_RegisterNewUser_Call) Return(userID int64, err error) *MockAuth_RegisterNewUser_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *MockAuth_RegisterNewUser_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (int64, error)) *MockAuth_RegisterNewUser_Call {
	_c.Call.Return(run)
	return _c
}
